### ISSUE TITLE
Fresh install?

### ISSUE THREAD

**Issue by reesericci** [mcaskill/fever#2]
When attempting to do a fresh install, after going through the installation process it just leaves me at a blank white screen and does not run the install-- I can visit the root page again and it shows the install wizard still.

**Comment by mcaskill** [comment]
You are most likely getting a blank page because `feedafever.com` is offline.

The original installation instructions will no longer work as originally intended because it involves making requests to `feedafever.com` to validate the installation and download additional files.

I commented out any server-side attempts to contact that host since its offline and to mitigate any risks if ever that host was taken over by a malicious actor.

You will need to checkout / put a copy of the `develop` branch in the desired document root, then create two files and define a bunch of PHP constants:

* `firewall/config/db.php`:
	* `FEVER_DB_SERVER`
	* `FEVER_DB_DATABASE`
	* `FEVER_DB_USERNAME`
	* `FEVER_DB_PASSWORD`
	* `FEVER_DB_PREFIX`
* `firewall/config/key.php`:
	* `ACTIVATION_KEY` — Your Activation Key from the email titled "Thank you for purchasing Fever" or, previously, by logging into your Fever Account Center.

If you want to be notified of updates (but you will have to manually update the installation), you can add the following constants to `firewall/config/key.php`:

* `FEVER_GITHUB_REPOSITORY` — Set to `mcaskill/fever`.
* `FEVER_GITHUB_API_TOKEN` — Create a Personal Access Token.

**Comment by reesericci** [comment]
Great! This worked for me - I couldn't find any docs on the constants before you sent that.
